markdown: kramdown
safe: false
permalink: /:categories/:title
exclude:
  - README.md

defaults:
  -
    scope:
        path: blog/_posts
        type: posts
    values:
        permalink: blog/:title
        layout: post
  -
    scope:
        path: contact/_posts
    values:
        layout: post
  -
    scope:
        path: articles/_posts
    values:
        layout: post        

blog:
    host: www.tiedaobing.cc
    name: 穿军装的石子
    desc: 一个铁道兵的回忆录，讲述青藏铁路一期工程施工连队的故事。

    category:
        articles: 篇章
        contact: 关于我
        blog: 博客
        
    categories:
      - name:  blog
        title: 博客

meta:
    author:
        name: 穿军装的石子
        email: qinglai1957@gmail.com
        disqus: cjzdsz                              # Disqus缩略标识
        gcse: 015688533063218008434:gvelfkn4n4o     # Google自定义搜索标识ID
        github: 3475651552                          # 微博账号
        gravatar: MNXKFuiajuutmtI026LZBe2ick9iaSJQtUKSoFPYASpNFRibZwaW9fuJTgOibYoJ3yARyl4ZEBQO4icfGZ9CnMObIM40L3NJ8ibXt7e/64                                  # Gravatar头像标识 38836deab9f6833754cd8f34f1f2cbf3

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: https://wx.qlogo.cn/mmopen/        # Gravatar头像服务器地址 https://s.gravatar.com/avatar/ http://en.gravatar.com/avatar/
